import type { Metadata } from "next";

import { APP_NAME } from "@/constants";
import { env } from "@/env";
import { decodeProfileShareToken } from "@/lib/profile-share";

interface ProfileSharePageProps {
  params: Promise<{
    locale: "ja" | "en";
    token: string;
  }>;
}

export async function generateMetadata({ params }: ProfileSharePageProps): Promise<Metadata> {
  const { locale, token } = await params;
  const path = `/${locale}/profile-share/${token}`;
  const decoded =
    env.PROFILE_SHARE_TOKEN_SECRET ? decodeProfileShareToken(token, env.PROFILE_SHARE_TOKEN_SECRET) : null;
  const imagePath = decoded?.imageUrl ?? `/api/og/profile/${token}`;

  return {
    title: `${APP_NAME} Profile Share`,
    description: "Tinder-style share card generated by marry.fun",
    openGraph: {
      title: `${APP_NAME} Profile Share`,
      description: "Tinder-style share card generated by marry.fun",
      url: path,
      images: [{ url: imagePath }],
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: `${APP_NAME} Profile Share`,
      description: "Tinder-style share card generated by marry.fun",
      images: [imagePath],
    },
  };
}

export default async function ProfileSharePage({ params }: ProfileSharePageProps) {
  const { locale } = await params;
  const heading = locale === "ja" ? "プロフィールをシェアしました" : "Profile shared successfully";
  const description =
    locale === "ja" ? "このページはXシェア用のOGカード表示に使われます。" : (
      "This page is used as the Open Graph card target for X sharing."
    );

  return (
    <main className="mx-auto flex min-h-dvh w-full max-w-2xl flex-col items-center justify-center gap-4 px-6 text-center text-white">
      <h1 className="text-2xl font-semibold">{heading}</h1>
      <p className="text-sm text-white/80">{description}</p>
    </main>
  );
}
